template: external-bridged-provider
provider: matchbox
organization: pulumiverse
major-version: 0
providerDefaultBranch: main
upstreamProviderOrg: poseidon
publishRegistry: false
enableAutoRelease: false
plugins:
  - name: terraform
    version: "1.0.19"
    kind: converter
languages:
  - dotnet
  - go
  - nodejs
  - python
publish:
  sdk: "all,!java"
  cdn: false
# license:
#   ignore:
    # Package is licensed under Apache 2.0 but license is not picked up correctly by the license detector
    # - github.com/OpenDNS/vegadns2client
pr-assign: ringods
pulumiConvert: 1